#!/usr/bin/env bash
set -euo pipefail

image="${XDG_STATE_HOME:-$HOME/.config/noctalia}/assets/images/wallpaper.jpg"
height=720

[[ -f "$image" ]] || {
    notify-send -i dialog-warning '404' "Error: Image not found at $image"
    exit 0
}

# Get original dimensions using ImageMagick
read -r real_width real_height <<< $(identify -format "%w %h" "$image")

# Calculate proportional width
width=$(( real_width * height / real_height ))

# Launch imv with a specific window class name
imv -c widget-img -W "$width" -H "$height" "$image"
