#!/usr/bin/env bash

# to handle clean exit when program is want to stop(Ctrl+C)
trap "exit 0" SIGINT SIGTERM

monitor="HDMI-A-1"

# declare func
get_monitor() {
    (driftwm msg state | awk -v mon="$monitor" '$1 == mon || $2 == mon {print mon}') 2>/dev/null | head -n 1
}

get_active_monitor() {
    # Memeriksa tanda bintang '*' murni di bawah blok outputs agar aman dari daftar windows
    (driftwm msg state | awk '/^outputs/ {in_outputs=1} in_outputs && $1 == "*" {print $2}') 2>/dev/null | head -n 1
}

# main script
while true; do
    # scanning/detecting external monitor by port VGA as DP-1
    # here | v | (the landing place of (CONTINUE 2))
    while [[ -z "$(get_monitor)" ]]; do
        sleep 2
    done

    # when external monitor just was detected
    if [[ "$(get_monitor)" == "$monitor" ]]; then        
        # automatically move the external monitor camera by driftwm when external monitor has been active(THE GOAL)
        while [[ "$(get_active_monitor)" != "$monitor" ]]; do
            if [[ -z "$(get_monitor)" ]]; then
                continue 2 # jump to | ^ |
            fi

            sleep 1
        done

        # move the external monitor camera by driftwm
        sleep 1.5
        driftwm msg camera 0 17

        # handle to detecting external monitor stay connected
        while [[ -n "$(get_monitor)" ]]; do
            sleep 2
        done
    fi

    sleep 1
done
