#!/usr/bin/env bash

# stop for a sec to make sure everthing is ready, main target is noctalia bar, yes only waiting for a bar ready
sleep 1.5

# then recenter home page point automatically
driftwm msg action home-toggle
