#!/usr/bin/env bash

# stop for a sec to make sure everthing is ready, main target is noctalia bar, yes only waiting for a bar ready
sleep 3

# then recenter home page point automatically
driftwm msg camera 0 17
